import type { TrackContent } from "@/lib/content-types";

export const dsa: TrackContent = {
  lessons: {
    "big-o-thinking": {
      body: [
        "Big-O is not math homework. It's a way to answer one question fast: if my input got 10x bigger, would my code fall over? That's it. You don't need to prove anything with formal notation to reason about it day to day — you need intuition you can apply in five seconds while looking at a loop.",
        "## The common classes, with real examples",
        "O(1) is a hash map lookup or array index access — constant no matter the size. O(log n) is binary search — you halve the problem every step, so even a billion items only takes ~30 steps. O(n) is a single loop through your data — a for loop over an array. O(n log n) is a good sort — merge sort, quicksort on average. O(n^2) is nested loops over the same data — comparing every pair. O(2^n) is exploring every subset — recursive Fibonacci without memoization. Learn to recognize these shapes in code, not just in equations.",
        "The trick most students miss: count the loops, not the lines. A single loop over n items is O(n) whether it has 3 lines or 300 lines inside it. Two nested loops over the same input is O(n^2), even if the inner loop looks short. If you call a function inside a loop, ask what that function costs — a hidden O(n) search inside an O(n) loop quietly becomes O(n^2).",
        "## Constants matter less than you think (until they don't)",
        "Big-O drops constants on purpose — O(2n) and O(n) are both 'O(n)' because we care about growth rate, not exact operation counts. For interviews and most real code, this is the right lens: an O(n) solution beats an O(n^2) one for large inputs regardless of small constant differences. But constants do matter in production systems at scale — a tight O(n) loop with cache-friendly memory access can beat a sloppy one. Just don't let that nuance stop you from learning the growth-rate intuition first. Get comfortable eyeballing complexity before you worry about micro-optimizing.",
        "One more habit worth building early: state the time AND space complexity out loud whenever you finish a solution, even in practice. It forces you to actually look at what you wrote instead of assuming it's fine. Recursive solutions especially hide space costs in the call stack — a recursive function that goes n levels deep uses O(n) space even if it never allocates an array.",
      ],
      takeaways: [
        "Big-O measures growth rate as input size increases, not exact speed.",
        "Count the loops (and hidden loops inside function calls) to spot complexity fast.",
        "Know the ladder by heart: O(1) < O(log n) < O(n) < O(n log n) < O(n^2) < O(2^n).",
        "Constants are dropped in Big-O notation but can still matter in real systems.",
        "Recursion has a space cost too — the call stack counts.",
      ],
      resources: [
        { title: "NeetCode Roadmap", url: "https://neetcode.io/roadmap", note: "Start here — it's organized by pattern, not random difficulty." },
        { title: "Big-O Cheat Sheet", url: "https://www.bigocheatsheet.com/", note: "Quick reference for common data structure and algorithm complexities." },
        { title: "VisuAlgo", url: "https://visualgo.net/en", note: "Visualize how algorithms actually run step by step." },
        { title: "LeetCode Explore: Big O", url: "https://leetcode.com/explore/", note: "Practice problems tagged by complexity class." },
      ],
      tryThis: "Pick 3 functions you've written recently and write down their time and space complexity from memory.",
    },
    "arrays-strings-hash-maps": {
      body: [
        "If you learn one data structure cold, make it the hash map. It turns O(n) lookups into O(1) ones, and an enormous share of interview problems boil down to 'have I seen this before' or 'what have I seen so far' — both are hash map questions. Whenever you catch yourself writing a nested loop to check if something exists in another collection, stop and ask if a hash map (or set) removes the inner loop entirely.",
        "## Two pointers: when order matters",
        "Two pointers is the move for sorted arrays or when you're comparing elements from different ends. Classic setup: one pointer at the start, one at the end, moving them toward each other based on a condition — like finding a pair that sums to a target in a sorted array. It turns an O(n^2) brute force into O(n) because each pointer only moves forward, never backward. The pattern also shows up in-place: fast and slow pointers within the same array, like removing duplicates without extra space.",
        "## Sliding window: when you care about a range",
        "Sliding window is two pointers' cousin, used for substring and subarray problems — 'longest substring without repeating characters,' 'smallest subarray with sum >= target.' You grow the window by moving the right pointer, and shrink it from the left when some condition breaks. The key insight is you never restart the window from scratch — that's what makes it O(n) instead of O(n^2). Practice recognizing the trigger words: 'contiguous,' 'substring,' 'subarray,' 'at most k,' 'longest/shortest.'",
        "These three tools — hash maps, two pointers, sliding window — cover a shocking percentage of array and string interview questions. Before reaching for anything fancier, ask: can a hash map track what I've seen? Is the array sorted, so two pointers apply? Am I looking for a contiguous range, so sliding window applies? Most of the time the answer is yes to one of these.",
      ],
      takeaways: [
        "Hash maps turn 'have I seen this' checks from O(n) to O(1).",
        "Two pointers works great on sorted data or when comparing from both ends.",
        "Sliding window avoids restarting from scratch on substring/subarray problems.",
        "Trigger words like 'contiguous' or 'longest substring' usually mean sliding window.",
        "Before writing a nested loop, ask if a hash map removes the inner loop.",
      ],
      resources: [
        { title: "NeetCode: Arrays & Hashing", url: "https://neetcode.io/roadmap", note: "Full curated set of arrays/hash map problems in order of difficulty." },
        { title: "LeetCode: Two Pointers Tag", url: "https://leetcode.com/tag/two-pointers/", note: "Filtered problem list to drill the pattern." },
        { title: "VisuAlgo: Hash Table", url: "https://visualgo.net/en/hashtable", note: "See collisions and lookups happen visually." },
        { title: "HackerRank: Arrays", url: "https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=arrays", note: "More reps on fundamentals." },
      ],
      tryThis: "Solve 'Two Sum' with a hash map, then solve it again on a sorted array using two pointers — compare the code.",
    },
    "linked-lists-stacks-queues": {
      body: [
        "Arrays are great until you need to insert or delete from the middle a lot, or you don't know the size ahead of time — that's when linked lists earn their keep. A linked list trades O(1) random access (you can't jump to index 5 instantly) for O(1) insertion/deletion once you're at the right node. Stacks and queues are linked lists (or arrays) with rules bolted on: stacks are last-in-first-out, queues are first-in-first-out.",
        "## When each one shines",
        "Use a stack for anything with nested or 'undo' structure — matching parentheses, browser back button, function call stacks, depth-first traversal. Use a queue for anything processed in arrival order — task scheduling, breadth-first traversal, print jobs. Use a linked list when you're frequently inserting/deleting in the middle of a sequence and don't need random access, like an LRU cache's internal ordering.",
        "## Reverse a linked list: the classic warm-up",
        "Reversing a singly linked list is the 'hello world' of linked list problems, and it's worth doing from memory until it's automatic. You keep three pointers: previous, current, and next. At each step you save the next node, point current's next back at previous, then shift all three pointers forward. It's O(n) time and O(1) space, and the exact same prev/curr/next pattern reappears in linked list cycle detection, reordering, and merging problems.",
        "## Valid parentheses: the classic stack warm-up",
        "The 'valid parentheses' problem is the stack equivalent of reversing a list — push opening brackets onto a stack, and when you hit a closing bracket, check it matches what's on top of the stack. If it doesn't match, or the stack's empty when you expect something, it's invalid. This 'push, then check against the top when you need to close something out' shape appears constantly: matching HTML tags, evaluating expressions, and undo/redo systems all use the same idea.",
        "Don't skip drawing these out on paper or a whiteboard app before coding. Pointer bugs in linked lists are almost always because you lost track of which node points where — a quick sketch saves you 10 minutes of debugging.",
      ],
      takeaways: [
        "Linked lists trade random access for cheap insert/delete in the middle.",
        "Stacks (LIFO) fit nested/undo problems; queues (FIFO) fit arrival-order problems.",
        "Reversing a list uses the prev/curr/next three-pointer pattern — memorize it.",
        "Valid parentheses is the template for any 'matching/closing' stack problem.",
        "Sketch pointer movements on paper before coding — it prevents most bugs.",
      ],
      resources: [
        { title: "NeetCode: Linked List", url: "https://neetcode.io/roadmap", note: "Ordered problem set covering reversal, cycles, merging." },
        { title: "LeetCode: Valid Parentheses", url: "https://leetcode.com/problems/valid-parentheses/", note: "The canonical stack warm-up problem." },
        { title: "VisuAlgo: Linked List", url: "https://visualgo.net/en/list", note: "Step through insert/delete/reverse operations visually." },
        { title: "HackerRank: Stacks and Queues", url: "https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=stacks", note: "More reps on the fundamentals." },
      ],
      tryThis: "Reverse a linked list on paper with prev/curr/next labeled, then translate it to code without looking at your notes.",
    },
    "trees-graphs": {
      body: [
        "Trees and graphs scare people because they feel abstract, but almost every problem reduces to two moves: breadth-first search (BFS) and depth-first search (DFS). A tree is just a graph with no cycles, so once you're comfortable with graph traversal, trees are the easy case. Get BFS and DFS solid and this whole category becomes much less intimidating.",
        "## BFS vs DFS: pick based on the question",
        "BFS explores level by level using a queue — it's your tool whenever you need the shortest path in an unweighted graph, or need to process things 'closest first' (level-order tree traversal, shortest path in a maze). DFS explores as deep as possible before backtracking, usually via recursion or an explicit stack — it's your tool for exploring all paths, detecting cycles, or when you need to fully process one branch before moving to the next (like validating a binary search tree).",
        "## Recursion mental models",
        "The trick to writing recursive tree/graph code without your brain melting: trust the recursive call. Assume the function already correctly solves the smaller subproblem (the left subtree, the right subtree, the next node), and just write the logic that combines those results. Don't try to trace every recursive call in your head — that's what stack overflows and headaches are made of. Also always define your base case first: what happens at a null node or an empty graph? Get that right and the rest usually falls out.",
        "## Problems secretly are graphs",
        "A lot of 'not obviously a graph' problems are graphs in disguise: word ladder (each word is a node, one-letter-different words are edges), course scheduling (course dependencies are directed edges — this is topological sort), number of islands (grid cells are nodes, adjacent land cells are edges), and social network 'friends of friends' queries. Whenever you see 'connections,' 'dependencies,' 'shortest path,' or a 2D grid of connected cells, consider modeling it as a graph before doing anything else — it usually simplifies the whole problem.",
        "Once you can confidently write BFS and DFS from scratch on both trees and general graphs (with a visited set!), you've unlocked a huge chunk of the interview problem space.",
      ],
      takeaways: [
        "Trees are graphs without cycles — master graph traversal and trees come free.",
        "BFS finds shortest paths in unweighted graphs; DFS explores full paths and detects cycles.",
        "Trust the recursive call — define the base case, then combine subresults.",
        "Grids, dependencies, and 'connections' problems are often graphs in disguise.",
        "Always track visited nodes in graph traversal to avoid infinite loops.",
      ],
      resources: [
        { title: "NeetCode: Trees & Graphs", url: "https://neetcode.io/roadmap", note: "Curated BFS/DFS problem progression." },
        { title: "VisuAlgo: Graph Traversal", url: "https://visualgo.net/en/dfsbfs", note: "Watch BFS and DFS run step by step." },
        { title: "LeetCode: Number of Islands", url: "https://leetcode.com/problems/number-of-islands/", note: "Great first 'grid is secretly a graph' problem." },
        { title: "HackerRank: Trees", url: "https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=trees", note: "More traversal reps." },
      ],
      tryThis: "Write BFS and DFS for a binary tree from scratch, without looking anything up, in under 10 minutes.",
    },
    "sorting-searching": {
      body: [
        "You will almost never implement sorting from scratch on the job — your language's built-in sort is fine. What matters is knowing conceptually how the major sorts work, because that understanding transfers to how you think about performance and to interview questions that build on top of sorting.",
        "## Know the big ones conceptually",
        "Bubble/insertion sort: O(n^2), fine for tiny or nearly-sorted data, not much else — know they exist and why they're rarely used. Merge sort: O(n log n) guaranteed, splits the array in half, sorts each half, merges them back together — stable and predictable, good mental model for divide-and-conquer generally. Quicksort: O(n log n) average but O(n^2) worst case, picks a pivot and partitions around it — usually faster in practice due to cache behavior, but the worst case matters for interview follow-up questions. You don't need to hand-implement all of these from memory, but you should be able to explain the tradeoffs of each in one sentence.",
        "## Binary search variants",
        "Binary search itself is simple: repeatedly halve a sorted search space. The part that trips people up is the variants — finding the first or last occurrence of a target, finding an insertion point, searching in a rotated sorted array, or searching an answer space (like 'minimum capacity to ship packages in D days') rather than an array. That last category — binary searching on the answer — is a pattern worth specifically drilling, because it doesn't look like a search problem at first glance; you binary search over possible answers and check if each candidate 'works.'",
        "The habit to build: whenever you see the word 'sorted' in a problem, or notice the answer space has a monotonic property (things get strictly better or worse as a value increases), binary search should be one of the first tools you consider — often before you write a single line of brute force.",
      ],
      takeaways: [
        "Know the tradeoffs of merge sort vs quicksort in one sentence each, not the full implementation from memory.",
        "Merge sort is stable and O(n log n) guaranteed; quicksort is usually faster but has an O(n^2) worst case.",
        "Binary search variants (first/last occurrence, rotated array, insertion point) are common interview twists.",
        "You can binary search over an answer space, not just an array — look for monotonic properties.",
        "The word 'sorted' in a problem is a strong hint to consider binary search.",
      ],
      resources: [
        { title: "NeetCode: Binary Search", url: "https://neetcode.io/roadmap", note: "Problem set covering the classic variants." },
        { title: "VisuAlgo: Sorting", url: "https://visualgo.net/en/sorting", note: "Watch each sorting algorithm run side by side." },
        { title: "LeetCode: Binary Search Tag", url: "https://leetcode.com/tag/binary-search/", note: "Filtered list to drill variants." },
        { title: "HackerRank: Sorting", url: "https://www.hackerrank.com/domains/algorithms?filters%5Bsubdomains%5D%5B%5D=sorting", note: "More conceptual reps." },
      ],
      tryThis: "Solve 'Search in Rotated Sorted Array' — it forces you to adapt plain binary search to a twisted condition.",
    },
    "dynamic-programming-basics": {
      body: [
        "DP has a reputation for being scary, mostly because people try to jump straight to the optimized bottom-up table solution. Don't. Every DP problem starts life as a plain recursive brute force solution — get that working first, then optimize.",
        "## Memoization first",
        "Write the brute force recursive solution the naive way, even if it's exponential and slow. Then find the repeated subproblems — usually you'll notice the same function arguments being computed over and over. Add a cache (a dictionary keyed by the arguments, or an array if the arguments are small integers) and check it before recomputing. That's memoization, aka 'top-down DP.' It's the same recursive code you already wrote, plus one cache check at the top and one cache write before returning. This step alone turns most exponential brute forces into polynomial time.",
        "## Bottom-up second",
        "Once memoization works, you can often convert it to a bottom-up 'tabulation' approach: instead of recursing from the big problem down to base cases, you iterate from the base cases up, filling a table (often just an array) until you reach the answer you originally wanted. Bottom-up avoids recursion overhead and stack depth limits, and it's often where the classic-looking 'DP table' solutions you see in textbooks come from. It's a nice-to-have after memoization works, not a requirement to start.",
        "## Recognizing DP",
        "The signal to look for: a problem asks for a count, a maximum/minimum, or a yes/no about ways to reach some goal, AND the problem can be broken into smaller versions of itself that overlap. 'Overlap' is the key word — plain recursion (like tree traversal) breaks a problem into non-overlapping subproblems, so there's nothing to cache. Classic starter DP problems worth doing in order: climbing stairs, house robber, coin change, longest increasing subsequence. Each builds on ideas from the last.",
        "Give yourself permission to be slow at DP for a while. It's the topic where 'do the brute force, then improve it' actually works as a study method — most people who claim they're 'good at DP' just have more of these patterns memorized than you do yet.",
      ],
      takeaways: [
        "Always write the brute force recursive solution first — DP is an optimization, not a starting point.",
        "Memoization is brute-force recursion plus a cache check and cache write.",
        "Bottom-up (tabulation) rebuilds the answer from base cases up, avoiding recursion overhead.",
        "Look for 'count/max/min/possible' questions with overlapping subproblems as the DP signal.",
        "Climbing stairs, house robber, coin change, and LIS are the right first problems to drill.",
      ],
      resources: [
        { title: "NeetCode: Dynamic Programming", url: "https://neetcode.io/roadmap", note: "Ordered from easy 1D DP to harder 2D problems." },
        { title: "LeetCode: Climbing Stairs", url: "https://leetcode.com/problems/climbing-stairs/", note: "The simplest possible DP starter problem." },
        { title: "LeetCode: Coin Change", url: "https://leetcode.com/problems/coin-change/", note: "Classic 'minimum number of ways' DP." },
        { title: "VisuAlgo: DP visualization", url: "https://visualgo.net/en", note: "Look under the DP-related modules for table-filling visuals." },
      ],
      tryThis: "Write the brute force recursive solution for 'Climbing Stairs,' then add memoization and time both versions.",
    },
    "interview-problem-patterns": {
      body: [
        "Here's the thing nobody tells you early enough: there are only about 10-15 real patterns behind the thousands of problems on LeetCode. Once you can recognize which pattern a problem belongs to, you're translating a known template instead of inventing a solution from scratch under time pressure.",
        "## The roughly 10 patterns worth knowing cold",
        "Two pointers, sliding window, fast/slow pointers (cycle detection), hash map for frequency/lookup, BFS/DFS on trees and graphs, binary search (including on answer spaces), backtracking (subsets, permutations, combinations), 1D and 2D dynamic programming, greedy (interval scheduling, activity selection), and topological sort (dependency ordering). If you can name the pattern within 60 seconds of reading a new problem, you're most of the way to solving it — the pattern tells you the shape of the code before you write a line.",
        "## Spaced repetition beats cramming",
        "Doing 200 problems in one frantic week before an interview mostly teaches you to recognize those exact 200 problems, not the underlying patterns. Spaced repetition — revisiting a problem you solved a week ago, then a month ago — is what moves a pattern from 'I followed a solution' to 'I recognize this instantly.' Keep a simple log: problem name, pattern, date solved, and a one-line note on what tripped you up. Revisit problems from that log on a rough weekly/monthly cadence instead of only doing new ones.",
        "## Quality over quantity",
        "It matters more that you deeply understand 100 well-chosen problems across all the patterns than that you've clicked 'submit' on 500 without reflecting. After solving a problem, spend two minutes writing down: which pattern was this, what was the trigger that told you which pattern to use, and could you solve a slightly different version of this from memory tomorrow? If you can't answer that last question, you haven't actually learned the problem yet — you've just seen the answer.",
        "This mindset shift — patterns over problem count — is the single biggest lever for interview prep efficiency. It's also exactly what the challenge for this module asks you to practice.",
      ],
      takeaways: [
        "About 10-15 patterns cover the vast majority of interview problems.",
        "Naming the pattern quickly tells you the shape of the solution before you code.",
        "Spaced repetition (revisiting old problems) beats cramming new ones.",
        "Keep a log: problem, pattern, date, and what tripped you up.",
        "If you can't solve a variant from memory later, you haven't learned the pattern yet.",
      ],
      resources: [
        { title: "NeetCode Roadmap", url: "https://neetcode.io/roadmap", note: "Organized by pattern — the best starting map for this module." },
        { title: "LeetCode Patterns Discussion", url: "https://leetcode.com/discuss/study-guide", note: "Community-maintained pattern breakdowns and study guides." },
        { title: "VisuAlgo", url: "https://visualgo.net/en", note: "Reinforce the underlying data structure behind each pattern." },
        { title: "HackerRank Interview Preparation Kit", url: "https://www.hackerrank.com/interview/interview-preparation-kit", note: "Pattern-grouped problem sets for structured practice." },
      ],
      tryThis: "Pick 3 solved problems from your history and label each with its underlying pattern before checking if you're right.",
    },
  },
  quiz: {
    id: "track-quiz",
    title: "Track 2 Quiz",
    questions: [
      {
        q: "Your code has a single loop through an array of n items, and inside the loop you call a function that does a hash map lookup. What's the overall time complexity?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"],
        answer: 2,
        explanation: "A hash map lookup is O(1), so a single loop calling it stays O(n) overall — no hidden nested loop is introduced.",
      },
      {
        q: "You need to find the longest substring without repeating characters. Which pattern fits best?",
        options: ["Binary search", "Sliding window", "Topological sort", "Bottom-up DP"],
        answer: 1,
        explanation: "'Substring' plus 'longest' with a contiguous range condition is the classic sliding window trigger.",
      },
      {
        q: "Which traversal should you use to find the shortest path in an unweighted graph?",
        options: ["DFS", "BFS", "Binary search", "Merge sort"],
        answer: 1,
        explanation: "BFS explores level by level, guaranteeing the first time you reach a node is via the shortest path in an unweighted graph.",
      },
      {
        q: "What's the correct first step when tackling a suspected DP problem?",
        options: [
          "Write the bottom-up table solution immediately",
          "Write the brute force recursive solution first",
          "Sort the input",
          "Convert it to a graph problem",
        ],
        answer: 1,
        explanation: "Every DP problem starts as a brute force recursive solution — you optimize into memoization and then tabulation from there.",
      },
      {
        q: "Why is spaced repetition recommended over cramming for interview problem patterns?",
        options: [
          "It's faster overall",
          "It helps you recognize patterns instead of memorizing specific problems",
          "It avoids needing to understand Big-O",
          "It only works for dynamic programming",
        ],
        answer: 1,
        explanation: "Revisiting problems over time moves the skill from 'I followed a solution' to genuine pattern recognition, which transfers to new problems.",
      },
    ],
  },
  challenge: {
    id: "track-challenge",
    title: "Challenge: Five Problems, Three Patterns",
    brief:
      "Pick 5 problems from the NeetCode roadmap that span at least 3 different patterns you've learned in this track (e.g. sliding window, BFS/DFS, DP). Solve each one, then write a one-line takeaway capturing the key insight — not just 'I solved it,' but what made it click.",
    steps: [
      "Pick 5 problems from the NeetCode roadmap covering at least 3 distinct patterns.",
      "Before coding, write down which pattern you think each problem uses and why.",
      "Solve each problem without looking at the solution for at least 20 minutes.",
      "For any problem you get stuck on, check the pattern (not the full solution) and retry.",
      "Write a one-line takeaway per problem describing the key insight that unlocked it.",
      "State the time and space complexity of each of your 5 solutions.",
      "A week later, re-solve one of the 5 from memory to confirm the pattern actually stuck.",
    ],
  },
};
