import type { TrackContent } from "@/lib/content-types";

export const programmingFoundations: TrackContent = {
  lessons: {
    "writing-clean-code": {
      body: [
        "Here's the thing nobody tells you in intro courses: code is read far more often than it's written. You'll write a function once and then read it — or someone else will read it — dozens of times while debugging, extending, or reviewing it. If you optimize for writing speed instead of reading speed, you're optimizing for the 10% case.",
        "## Naming is not decoration",
        "A variable named `x` or `data` or `temp` tells the reader nothing. A variable named `unpaidInvoices` tells them everything. Good names let you delete comments, because the comment was just explaining a bad name. Spend the extra five seconds. Future-you, at 1am before a deadline, will thank present-you.",
        "The same goes for functions. `processStuff()` is a red flag. `sendWelcomeEmail()` tells you exactly what happens when you call it, with no need to open the file. If you can't name a function clearly, that's often a sign it's doing too many things.",
        "## Small functions, single responsibility",
        "A function that fits on one screen and does one job is easy to test, easy to reuse, and easy to reason about. A 200-line function that validates input, hits the database, formats output, and logs errors is none of those things. Break it apart. Each piece gets its own name, and the name documents intent.",
        "This isn't about arbitrary line-count rules — it's about cognitive load. When you open a function, you should be able to hold its entire behavior in your head. If you can't, it's doing too much.",
        "## Readability beats cleverness",
        "There's a trap junior engineers fall into: showing off. A one-liner with three nested ternaries and a regex feels impressive to write. It's a nightmare to review six months later, including for you. The engineer who writes the boring, obvious version that a tired teammate can understand at 5pm on a Friday is doing better work than the one chasing clever one-liners.",
        "Clean code isn't about following a style guide to the letter — it's a habit of empathy for the next reader. Every time you write a line, ask: if I'd never seen this before, would I get it in five seconds? If not, rename, restructure, or add the smallest comment necessary to bridge the gap.",
      ],
      takeaways: [
        "Code is read far more than it's written — optimize for the reader, not the writer.",
        "Names should make comments unnecessary; vague names like `data` or `temp` are a smell.",
        "Keep functions small and single-purpose so you can hold their behavior in your head.",
        "Clever one-liners cost more in review time than they save in typing time.",
        "Ask 'would a tired teammate understand this in five seconds?' before moving on.",
      ],
      resources: [
        { title: "The Odin Project — Foundations", url: "https://www.theodinproject.com/paths/foundations", note: "Free curriculum with strong emphasis on writing readable code from day one." },
        { title: "Exercism", url: "https://exercism.org/", note: "Practice exercises with mentor feedback focused partly on code style, not just correctness." },
        { title: "MIT Missing Semester", url: "https://missing.csail.mit.edu/", note: "Covers the practical engineering habits CS classes skip, including tooling that supports clean code." },
        { title: "Google Style Guides", url: "https://google.github.io/styleguide/", note: "Real-world naming and formatting conventions used at scale." },
      ],
      tryThis: "Open your last homework file and rename every variable that isn't immediately obvious out of context.",
    },
    "language-mastery-pick-your-primary-language": {
      body: [
        "It's tempting to sample every language — Python one week, Rust the next, a bit of Go because it's trendy. Breadth has its place later, but early on, depth in one language pays off more. Pick one (Python, JavaScript/TypeScript, and Java are all solid, employable choices) and go deep enough that you stop translating from another language in your head.",
        "## What depth actually looks like",
        "Depth isn't knowing every keyword. It's knowing the idioms: the way experienced developers in that language actually solve common problems. In Python that's list comprehensions and context managers. In JavaScript that's array methods like `map`/`filter`/`reduce` instead of manual loops. Idiomatic code is easier for other people in that ecosystem to read and trust.",
        "## Standard library fluency",
        "A huge amount of junior-engineer time is wasted reinventing something the standard library already does well — parsing dates, deduplicating a list, reading a file. Before you write a helper function, check if the language already gives you one. Spend an afternoon just skimming your language's standard library docs table of contents. You won't remember everything, but you'll remember it exists, which is enough to know when to go look it up.",
        "This also means learning to read official documentation without flinching. Docs are denser than tutorials, but they're the source of truth, and tutorials go stale.",
        "## Depth compounds",
        "Once you're fluent in one language's mental model — how it handles memory, errors, typing, concurrency — picking up a second language is dramatically faster, because you're mapping new syntax onto concepts you already understand instead of learning everything from scratch. Interviewers and teammates also trust someone who clearly knows one language well over someone who knows five languages shallowly.",
      ],
      takeaways: [
        "Pick one primary language and go deep before spreading thin across many.",
        "Idiomatic code (using the language's own patterns) is more valuable than 'technically works' code.",
        "Standard library fluency saves you from reinventing wheels — check before you build.",
        "Deep knowledge of one language transfers and makes learning your second language much faster.",
        "Get comfortable reading official docs, not just tutorials.",
      ],
      resources: [
        { title: "Python Official Docs", url: "https://docs.python.org/3/", note: "The source of truth for the standard library — practice navigating it directly." },
        { title: "MDN Web Docs (JavaScript)", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript", note: "The best reference for JS/TS idioms and built-in methods." },
        { title: "Exercism", url: "https://exercism.org/", note: "Language-specific tracks that push you toward idiomatic solutions via mentor feedback." },
        { title: "freeCodeCamp", url: "https://www.freecodecamp.org/", note: "Structured, project-based practice to build depth in one language." },
      ],
      tryThis: "Pick one function you wrote from scratch recently and find the standard library method that does the same thing.",
    },
    "debugging-like-a-detective": {
      body: [
        "Debugging is a skill, not luck, and it's one CS courses barely teach. The difference between a junior who spends four hours flailing and a senior who fixes the same bug in ten minutes usually isn't experience with that exact bug — it's a systematic process.",
        "## Reproduce before you touch anything",
        "The first rule: don't start changing code until you can reliably make the bug happen. If you can't reproduce it, you can't verify you fixed it — you're just guessing and hoping. Find the smallest set of steps or inputs that trigger it every time. This alone eliminates most wasted effort.",
        "## Binary search the problem space",
        "Once you can reproduce it, narrow it down by half at a time. Comment out half the code — does the bug still happen? Check the middle of the pipeline — is the data still correct there? This is the same idea as binary search in an array: you don't need to check every line, you need to keep cutting the suspect area in half until only one place is left.",
        "## Read stack traces from the bottom up... sometimes both ways",
        "A stack trace can look intimidating, but the actual error message and the line that threw it are usually at the top, while the bottom shows how execution got there. Read the top line first for what broke, then scan down through the call chain to see where it started. Don't panic-read the whole wall of text — find the first line in the trace that's actually your code, not library code, because that's usually where the real bug lives.",
        "## Rubber ducking works because explaining forces clarity",
        "Explaining your code line by line to a rubber duck, a friend, or even an empty chair forces you to slow down and state assumptions out loud. Most of the time you'll catch the bug mid-sentence, because bugs hide in the gap between what you think the code does and what it actually does — and narrating closes that gap.",
        "Put these together and debugging stops being panic and starts being a process: reproduce, narrow, read carefully, explain out loud. It works on a 10-line script and it works on a production outage.",
      ],
      takeaways: [
        "Always reproduce the bug reliably before attempting a fix.",
        "Binary search the code or data to narrow down where the problem lives.",
        "Find the first line in a stack trace that's your own code — that's usually the real clue.",
        "Rubber ducking works because narrating your code out loud exposes wrong assumptions.",
        "Debugging is a repeatable process, not a matter of luck or experience alone.",
      ],
      resources: [
        { title: "MIT Missing Semester — Debugging & Profiling", url: "https://missing.csail.mit.edu/2020/debugging-profiling/", note: "A lecture built exactly around this systematic approach to debugging." },
        { title: "Exercism", url: "https://exercism.org/", note: "Failing test suites are a low-stakes way to practice reproducing and isolating bugs." },
        { title: "Chrome DevTools Debugging Docs", url: "https://developer.chrome.com/docs/devtools/javascript/", note: "Hands-on reference for stepping through code and reading stack traces in the browser." },
        { title: "Python Debugging with pdb", url: "https://docs.python.org/3/library/pdb.html", note: "The built-in Python debugger — learn it once, use it everywhere." },
      ],
      tryThis: "Next bug you hit, write down the exact reproduction steps before you change a single line of code.",
    },
    "reading-other-people-s-code": {
      body: [
        "This is the most underrated skill in the industry. Almost nobody joins a job and writes on a blank canvas — you join a codebase with thousands of existing files, and your first real task is understanding what's already there before you can safely add to it. Yet most CS programs only ever have you write your own code from scratch.",
        "## Start at the entry point",
        "Don't try to read a codebase file by file, top to bottom — you'll drown. Instead, find where execution starts: the `main` function, the route handler for a specific URL, the button's `onClick`. Then follow the thread from there, only going as deep as you need to answer your current question.",
        "## Trace one feature end to end",
        "Pick a single, concrete feature — say, 'what happens when a user clicks Submit on the signup form' — and trace it through every file it touches, from the UI to the database call and back. Ignore everything unrelated. This gives you a real mental map of how the pieces connect, which is far more useful than reading every file in isolation.",
        "## Use your tools, not just your eyes",
        "Use 'find usages' / 'go to definition' in your editor instead of scrolling and guessing. Search the codebase for a function name to see every place it's called. Read tests before you read implementation — tests often describe intended behavior more clearly than the code itself, especially in messy legacy code.",
        "## It compounds fast",
        "The first unfamiliar codebase you read will take you days to feel oriented in. The tenth will take you an hour, because you'll recognize common patterns: this looks like an MVC structure, this is a typical REST API layout, this test file tells me the shape of the whole module. Treat reading code as deliberate practice, the same way you'd practice writing it — pick an open-source project you use and just read a piece of it for twenty minutes, no goal other than understanding.",
      ],
      takeaways: [
        "Reading code well is arguably more valuable on the job than writing it from scratch.",
        "Start at an entry point (main, a route, a button handler) rather than reading top to bottom.",
        "Trace one concrete feature end to end to build a real mental map of the system.",
        "Use 'go to definition' and 'find usages' instead of scrolling and guessing.",
        "Tests often explain intended behavior faster than the implementation code does.",
      ],
      resources: [
        { title: "MIT Missing Semester — Editors", url: "https://missing.csail.mit.edu/2020/editors/", note: "Covers navigation tools (go-to-definition, search) that make reading unfamiliar code far faster." },
        { title: "GitHub Explore", url: "https://github.com/explore", note: "Browse real, popular open-source repos to practice reading production code." },
        { title: "The Odin Project", url: "https://www.theodinproject.com/", note: "Its projects reference real repos and encourage reading other students' solutions." },
        { title: "freeCodeCamp — Reading Other People's Code", url: "https://www.freecodecamp.org/news/tag/reading-code/", note: "Articles specifically on strategies for navigating unfamiliar codebases." },
      ],
      tryThis: "Pick an open-source repo you use, find its entry point, and trace one feature through the code for 20 minutes.",
    },
    "code-review-etiquette": {
      body: [
        "Code review is where a lot of your actual growth as an engineer happens, but only if you approach it right on both sides — as the person receiving feedback and the person giving it.",
        "## Receiving feedback without ego",
        "The moment you frame a review comment as an attack, you stop learning from it. A comment like 'this could leak memory if the loop doesn't exit' is about the code, not about you. Default assumption: the reviewer wants the project to succeed and is spending their time to help you, not to score points. If a comment stings, that's a sign to slow down and ask a clarifying question instead of getting defensive in the reply.",
        "## Giving feedback kindly but honestly",
        "When you're the one reviewing, remember someone put real effort into that PR, possibly stayed late to finish it. Vague feedback like 'this is messy' helps nobody — be specific: 'this function does three things, consider splitting it into X and Y.' Ask questions instead of issuing commands when you're not sure: 'what happens if this list is empty?' invites a conversation instead of a fight.",
        "## Review the code, not the person",
        "'This variable name is confusing' is fine. 'You always write confusing names' is not — it turns a technical conversation into a personal one, and people get defensive fast. Keep comments scoped to this diff, this line, this decision. And say what's good, not just what's wrong — if someone handled an edge case well, say so. It costs nothing and it makes the rest of the feedback land better.",
        "## Small, frequent PRs make everything easier",
        "A 40-file PR is exhausting to review carefully, so reviewers skim it and miss real issues. A 200-line PR gets read properly. If you're the author, breaking work into smaller chunks isn't just a courtesy — it gets you better, more thorough feedback, faster, and it makes it much easier to spot exactly which change introduced a bug later.",
      ],
      takeaways: [
        "Treat review comments as being about the code, not a judgment of you as a person.",
        "Give specific, actionable feedback instead of vague criticism like 'this is messy.'",
        "Frame uncertain feedback as questions to invite discussion instead of confrontation.",
        "Call out what's done well, not only what needs to change.",
        "Smaller, more frequent PRs get better and faster reviews than large ones.",
      ],
      resources: [
        { title: "Google's Code Review Developer Guide", url: "https://google.github.io/eng-practices/review/", note: "Industry-standard guidance for both giving and receiving code review, from Google's own engineering practices." },
        { title: "GitHub Docs — About Pull Request Reviews", url: "https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews", note: "The mechanics of how PR review actually works on GitHub." },
        { title: "MIT Missing Semester — Version Control (Git)", url: "https://missing.csail.mit.edu/2020/version-control/", note: "Covers the git workflow that PRs and reviews are built on top of." },
        { title: "The Odin Project — Pull Requests", url: "https://www.theodinproject.com/lessons/foundations-pull-requests", note: "A practical primer on submitting and reviewing PRs as a beginner." },
      ],
      tryThis: "Next time you leave PR feedback (or comment on a friend's code), rewrite one vague comment into a specific, actionable one.",
    },
  },
  quiz: {
    id: "track-quiz",
    title: "Track 1 Quiz",
    questions: [
      {
        q: "Why does naming matter so much more than it seems like it should?",
        options: [
          "It makes autocomplete faster",
          "Code is read far more often than it's written, so good names save every future reader time",
          "It's required by most compilers",
          "It only matters for public APIs",
        ],
        answer: 1,
        explanation: "Clear names reduce the need for comments and make code understandable to anyone reading it later, which happens far more often than writing it.",
      },
      {
        q: "What's the main benefit of going deep on one programming language before spreading across many?",
        options: [
          "Other languages become irrelevant",
          "Deep understanding of one language's mental model transfers and makes learning the next one faster",
          "It guarantees a higher salary",
          "You never need to read documentation again",
        ],
        answer: 1,
        explanation: "Once you understand core concepts deeply in one language, you map new syntax onto that understanding instead of learning everything from scratch.",
      },
      {
        q: "What should you do before making any code changes when debugging?",
        options: [
          "Rewrite the function from scratch",
          "Add print statements everywhere",
          "Reliably reproduce the bug so you can verify a fix later",
          "Push to production and check logs",
        ],
        answer: 2,
        explanation: "Without a reliable reproduction, you can't confirm whether your change actually fixed anything.",
      },
      {
        q: "What's the recommended way to start understanding an unfamiliar codebase?",
        options: [
          "Read every file top to bottom in alphabetical order",
          "Find an entry point and trace one feature end to end",
          "Memorize the folder structure first",
          "Rewrite it in a language you know better",
        ],
        answer: 1,
        explanation: "Starting from an entry point and following one concrete feature builds a real mental map without drowning in unrelated code.",
      },
      {
        q: "What's the best way to phrase code review feedback you're not fully sure about?",
        options: [
          "State it as a firm command",
          "Skip it to avoid conflict",
          "Ask a clarifying question, like 'what happens if this list is empty?'",
          "Leave it as a private message instead of on the PR",
        ],
        answer: 2,
        explanation: "Framing uncertain feedback as a question invites discussion rather than putting the author on the defensive.",
      },
    ],
  },
  challenge: {
    id: "track-challenge",
    title: "Challenge: Refactor an Old Project",
    brief:
      "Dig up one of your old class projects — the messier the better. You're going to apply everything from this track to it: clean up naming, break apart at least one oversized function, and document it properly with a README, as if you were handing it off to a new teammate.",
    steps: [
      "Pick an old project with at least one function you're embarrassed by",
      "Rename every unclear variable and function so a stranger could understand them without comments",
      "Find your largest function and extract at least 3 smaller functions with single responsibilities",
      "Trace through the code once, end to end, as if you were reading someone else's work for the first time",
      "Write a README explaining what the project does, how to run it, and any known limitations",
      "Open a self pull request (or diff) and leave review comments on your own old code, as practice giving feedback",
      "Push the refactor and compare the before/after — note what got easier to read",
    ],
  },
};
