import type { Resource } from "@/lib/content-types";

export const RESOURCE_REGISTRY: Record<string, Resource> = {
  cs50: { id: "cs50", label: "CS50", url: "https://cs50.harvard.edu/x/", free: true },
  freecodecamp: { id: "freecodecamp", label: "freeCodeCamp", url: "https://www.freecodecamp.org/", free: true },
  code_org: { id: "code_org", label: "Code.org", url: "https://code.org/", free: true },
  scratch: { id: "scratch", label: "Scratch", url: "https://scratch.mit.edu/", free: true },
  github_pages_docs: { id: "github_pages_docs", label: "GitHub Pages Docs", url: "https://docs.github.com/en/pages", free: true },
  mit_app_inventor: { id: "mit_app_inventor", label: "MIT App Inventor", url: "https://appinventor.mit.edu/", free: true },
  khan_academy_cs: { id: "khan_academy_cs", label: "Khan Academy CS", url: "https://www.khanacademy.org/computing/computer-programming", free: true },
  w3schools: { id: "w3schools", label: "W3Schools", url: "https://www.w3schools.com/", free: true },
  odin_project: { id: "odin_project", label: "The Odin Project", url: "https://www.theodinproject.com/", free: true },
  mdn: { id: "mdn", label: "MDN Web Docs", url: "https://developer.mozilla.org/", free: true },
  roadmap_sh: { id: "roadmap_sh", label: "roadmap.sh", url: "https://roadmap.sh/", free: true },
  missing_semester: { id: "missing_semester", label: "The Missing Semester (MIT)", url: "https://missing.csail.mit.edu/", free: true },
  exercism: { id: "exercism", label: "Exercism", url: "https://exercism.org/", free: true },
  python_docs: { id: "python_docs", label: "Python Official Docs", url: "https://docs.python.org/3/", free: true },
  javascript_docs: { id: "javascript_docs", label: "JavaScript Docs (MDN)", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript", free: true },
  java_docs: { id: "java_docs", label: "Java Official Docs", url: "https://docs.oracle.com/en/java/", free: true },
  neetcode: { id: "neetcode", label: "NeetCode", url: "https://neetcode.io/", free: true },
  leetcode: { id: "leetcode", label: "LeetCode", url: "https://leetcode.com/", free: true },
  hackerrank: { id: "hackerrank", label: "HackerRank", url: "https://www.hackerrank.com/", free: true },
  visualgo: { id: "visualgo", label: "VisuAlgo", url: "https://visualgo.net/en", free: true },
  learn_git_branching: { id: "learn_git_branching", label: "Learn Git Branching", url: "https://learngitbranching.js.org/", free: true },
  github_docs: { id: "github_docs", label: "GitHub Docs", url: "https://docs.github.com/", free: true },
  oh_shit_git: { id: "oh_shit_git", label: "Oh Shit Git", url: "https://ohshitgit.com/", free: true },
  pro_git: { id: "pro_git", label: "Pro Git Book", url: "https://git-scm.com/book/en/v2", free: true },
  full_stack_open: { id: "full_stack_open", label: "Full Stack Open", url: "https://fullstackopen.com/en/", free: true },
  sqlbolt: { id: "sqlbolt", label: "SQLBolt", url: "https://sqlbolt.com/", free: true },
  postgresql_tutorial: { id: "postgresql_tutorial", label: "PostgreSQL Tutorial", url: "https://www.postgresqltutorial.com/", free: true },
  test_automation_university: { id: "test_automation_university", label: "Test Automation University", url: "https://testautomationu.applitools.com/", free: true },
  jest_docs: { id: "jest_docs", label: "Jest Docs", url: "https://jestjs.io/docs/getting-started", free: true },
  pytest_docs: { id: "pytest_docs", label: "pytest Docs", url: "https://docs.pytest.org/", free: true },
  docker_get_started: { id: "docker_get_started", label: "Docker Get Started", url: "https://docs.docker.com/get-started/", free: true },
  system_design_primer: { id: "system_design_primer", label: "System Design Primer (GitHub)", url: "https://github.com/donnemartin/system-design-primer", free: true },
  bytebytego: { id: "bytebytego", label: "ByteByteGo (free)", url: "https://bytebytego.com/", free: true },
  anthropic_docs: { id: "anthropic_docs", label: "Anthropic Docs", url: "https://docs.anthropic.com/", free: true },
  openai_docs: { id: "openai_docs", label: "OpenAI Docs", url: "https://platform.openai.com/docs/overview", free: true },
  three_blue_one_brown_nn: { id: "three_blue_one_brown_nn", label: "3Blue1Brown Neural Networks", url: "https://www.3blue1brown.com/topics/neural-networks", free: true },
  tech_interview_handbook: { id: "tech_interview_handbook", label: "Tech Interview Handbook", url: "https://www.techinterviewhandbook.org/", free: true },
  levels_fyi: { id: "levels_fyi", label: "levels.fyi", url: "https://www.levels.fyi/", free: true },
  interviewing_io: { id: "interviewing_io", label: "interviewing.io", url: "https://interviewing.io/", free: true },
  pramp: { id: "pramp", label: "Pramp", url: "https://www.pramp.com/", free: true },
};

export const RESOURCE_LIST = Object.values(RESOURCE_REGISTRY);
