import type { TrackContent } from "@/lib/content-types";

export const testing: TrackContent = {
  lessons: {
    "why-tests-matter": {
      body: [
        "Every codebase you'll ever touch changes constantly. Requirements shift, bugs get found, features get bolted on. The question isn't whether your code will change — it's whether you'll know when a change breaks something. Tests are how you know.",
        "## The safety net, not the speed bump",
        "New engineers often think of tests as overhead — something that slows down shipping. Flip that: tests are what let you ship fast without fear. Without them, every change is a guess. You make the edit, run the app manually, click around, hope you didn't miss anything, and ship. With tests, you make the edit, run a command, and get a yes/no answer in seconds about whether you broke the parts of the system you didn't mean to touch.",
        "This matters most on code you didn't write yourself, or code you wrote six months ago and have forgotten the details of. A good test suite is documentation that can't lie — it's an executable description of what the system is supposed to do. Comments go stale. Tests fail loudly when they go stale, which forces someone to fix them or delete them.",
        "## Confidence to refactor",
        "The real payoff of tests shows up when you need to refactor — restructure code without changing its behavior. Refactoring without tests is terrifying, so people avoid it, and codebases rot: duplicated logic, tangled dependencies, functions nobody dares touch. Refactoring with tests is routine: you change the internals, run the suite, and if it's green, you're done. That loop — change, verify, repeat — is what lets teams keep codebases healthy for years instead of rewriting them every 18 months.",
        "This doesn't mean test everything, always, at 100% coverage. It means test the things that would hurt if they silently broke: core business logic, payment paths, auth, anything with tricky edge cases. Coverage is a means, not a goal — a codebase with 100% coverage and no meaningful assertions is worse than one with 60% coverage that actually checks behavior that matters.",
        "## What tests actually buy you",
        "Tests catch regressions before users do. They let you onboard faster onto unfamiliar code, because you can read the tests to understand intended behavior. They make code reviews faster, because reviewers can trust the suite instead of manually re-deriving every edge case. And they change how you write code in the first place — code that's easy to test tends to be smaller, more decoupled, and easier to reason about. That's not a coincidence; testability and good design are the same thing viewed from different angles.",
      ],
      takeaways: [
        "Tests are what let you ship changes fast without fear, not overhead that slows you down.",
        "A test suite is executable documentation — it can't silently go stale like comments can.",
        "Tests give you the confidence to refactor, which is how codebases stay healthy long-term.",
        "Prioritize testing logic that would actually hurt if it broke silently, not 100% coverage for its own sake.",
        "Code that's easy to test is usually just better-designed code.",
      ],
      resources: [
        { title: "Test Automation University", url: "https://testautomationu.applitools.com/", note: "Free courses on testing fundamentals and tools, from a former Selenium maintainer's org." },
        { title: "Why Test?", url: "https://kentcdodds.com/blog/why-write-tests", note: "Kent C. Dodds on the actual business case for writing tests." },
        { title: "Static vs Unit vs Integration vs E2E Testing for Frontend Apps", url: "https://kentcdodds.com/blog/unit-vs-integration-vs-e2e-tests", note: "Sets up vocabulary you'll use for the rest of this track." },
      ],
      tryThis: "Find a bug you fixed recently and write down: would a test have caught it before it shipped?",
    },
    "unit-testing": {
      body: [
        "A unit test checks one small piece of behavior — a function, a method, a component — in isolation from the rest of the system. It's the cheapest, fastest kind of test you can write, and it should make up the bulk of your test suite.",
        "## Arrange, act, assert",
        "Almost every good unit test follows the same three-step shape. Arrange: set up the inputs and any state you need. Act: call the thing you're testing. Assert: check that the output or side effect matches what you expected. Keeping these three steps visually separate — even with blank lines or comments — makes tests easy to scan. When a test fails, you want to immediately see what was set up, what happened, and what was expected, without untangling a wall of logic.",
        "```\ntest('applies a percentage discount to the total', () => {\n  // arrange\n  const cart = { total: 100 };\n\n  // act\n  const result = applyDiscount(cart, 0.2);\n\n  // assert\n  expect(result.total).toBe(80);\n});\n```",
        "## Test behavior, not implementation",
        "This is the single biggest thing that separates useful tests from annoying ones. A test should verify what a function does, not how it does it. If you test internal details — private helper functions, the exact sequence of internal calls, internal variable names — your tests break every time you refactor, even when the actual behavior is unchanged. That trains people to distrust or ignore failing tests, which defeats the whole purpose.",
        "Instead, test through the public interface: given this input, what output or observable effect do you get? If you change how applyDiscount is implemented internally but it still returns the correct total for the same inputs, the test shouldn't need to change. That's the sign you're testing the right layer.",
        "## Name tests as sentences",
        "A test name should read like a sentence describing behavior: 'applies a percentage discount to the total', not 'test1' or 'testApplyDiscount'. When a test fails in CI, the name is often the first and only thing someone reads before deciding whether it's urgent. Good names turn a red test suite into a readable list of exactly what broke, without anyone having to open the file.",
        "Aim for small, focused tests — one logical assertion (or a tight cluster of related ones) per test. If a test has ten unrelated assertions, a failure tells you almost nothing about what actually went wrong. Fast, isolated, well-named unit tests are what make a suite something people actually run constantly instead of dreading.",
      ],
      takeaways: [
        "Structure tests as arrange, act, assert — it makes failures easy to read at a glance.",
        "Test behavior through the public interface, not internal implementation details.",
        "Tests coupled to implementation break on every refactor and erode trust in the suite.",
        "Name tests as sentences describing behavior so failures are self-explanatory.",
        "Keep tests small and focused so a failure points at exactly one thing.",
      ],
      resources: [
        { title: "Jest Documentation — Getting Started", url: "https://jestjs.io/docs/getting-started", note: "The standard JS testing framework; this is where to start." },
        { title: "pytest Documentation", url: "https://docs.pytest.org/en/stable/", note: "The standard Python testing framework, if that's your stack." },
        { title: "Testing Implementation Details", url: "https://kentcdodds.com/blog/testing-implementation-details", note: "Kent C. Dodds on why implementation-coupled tests hurt you." },
        { title: "Test Automation University", url: "https://testautomationu.applitools.com/", note: "Hands-on courses covering unit testing patterns across languages." },
      ],
      tryThis: "Pick one pure function in a project of yours and write three unit tests for it: a typical case, an edge case, and an error case.",
    },
    "integration-end-to-end-testing": {
      body: [
        "Unit tests check pieces in isolation. But real bugs often live in the seams — where your code talks to a database, an API, another module, or the browser. Integration and end-to-end (E2E) tests check that those pieces work together correctly.",
        "## The testing pyramid",
        "The classic mental model is a pyramid with three layers. At the base: lots of unit tests — fast, cheap, isolated, testing individual functions and components. In the middle: fewer integration tests — checking that multiple units work together correctly, like a service talking to a real (or realistic) database. At the top: a small number of end-to-end tests — driving the whole app like a real user would, often through a real browser, checking that a full user flow (sign up, add to cart, checkout) actually works start to finish.",
        "The shape matters because of cost. Unit tests run in milliseconds and pinpoint failures precisely. E2E tests can take seconds or minutes each, are more brittle (a CSS change can break a test that has nothing to do with the logic being tested), and when they fail, they tell you something is wrong somewhere in a large surface area, not exactly where. That's why you want many unit tests, a moderate number of integration tests, and a small, carefully chosen set of E2E tests covering your most critical user flows.",
        "## Tradeoffs per layer",
        "Integration tests catch a category of bugs unit tests structurally cannot: mismatched contracts between modules, wrong SQL queries against a real schema, serialization bugs, auth middleware that blocks a request unexpectedly. They cost more to write and run than unit tests but far less than E2E tests, and they're usually where you get the best bang for your effort once you have basic unit coverage.",
        "E2E tests are worth it for the handful of flows that would be a genuine crisis if broken — checkout, login, the core action your product exists to perform. They're not worth it for every possible click path in your app; that way lies a slow, flaky test suite that takes 40 minutes to run and that everyone starts ignoring or disabling. Flaky E2E tests are worse than no E2E tests, because they teach your team to distrust red builds.",
        "A practical rule: when you find a real production bug, ask which layer would have caught it cheapest. Sometimes the honest answer is a unit test you didn't write. Sometimes it's genuinely an integration issue that only an integration test would catch. Let real bugs guide where you invest, rather than trying to cover every layer equally from day one.",
      ],
      takeaways: [
        "Unit tests check isolated pieces; integration tests check pieces working together; E2E tests check full user flows.",
        "The testing pyramid — many unit tests, fewer integration, fewest E2E — balances speed against realism.",
        "Integration tests catch contract mismatches and wiring bugs that unit tests structurally can't.",
        "E2E tests are valuable but slow and brittle — reserve them for your most critical flows.",
        "Flaky tests are worse than no tests; they teach people to ignore red builds.",
      ],
      resources: [
        { title: "Static vs Unit vs Integration vs E2E Testing for Frontend Apps", url: "https://kentcdodds.com/blog/unit-vs-integration-vs-e2e-tests", note: "Direct breakdown of the layers and where to invest effort." },
        { title: "Test Automation University", url: "https://testautomationu.applitools.com/", note: "Includes dedicated courses on E2E frameworks like Playwright and Cypress." },
        { title: "Jest Documentation — Testing Asynchronous Code", url: "https://jestjs.io/docs/asynchronous", note: "Relevant once your tests start hitting real async integrations." },
        { title: "pytest Documentation — Fixtures", url: "https://docs.pytest.org/en/stable/how-to/fixtures.html", note: "How pytest sets up realistic state for integration-level tests." },
      ],
      tryThis: "Write one integration test for a piece of your Track 4 project that touches a database or API, using a real or in-memory version of that dependency.",
    },
    "test-driven-development-intro": {
      body: [
        "Test-driven development (TDD) flips the usual order: you write a failing test for behavior that doesn't exist yet, write the minimum code to make it pass, then clean up. It's a discipline, not a religion, and it's worth understanding honestly — including when it's not the right tool.",
        "## Red, green, refactor",
        "The cycle has three steps, repeated in tight loops. Red: write a test for a small piece of behavior you haven't built yet. Run it — it fails, because the code doesn't exist. Green: write the simplest possible code that makes the test pass, even if it's ugly or hard-coded. Refactor: now that you have a passing test as a safety net, clean up the implementation — remove duplication, improve names, generalize — without changing behavior, running the test after each change to confirm you haven't broken it.",
        "The discipline of writing the test first forces you to think about the interface and the expected behavior before you think about the implementation. It also guarantees you have test coverage for everything you build, because nothing gets written without a test demanding it first.",
        "## When it genuinely helps",
        "TDD shines on logic with clear, well-defined inputs and outputs — parsers, calculators, validation rules, algorithms, anything where you can state 'given X, expect Y' before writing a line of implementation. It's also valuable when you're fixing a bug: write a test that reproduces the bug (red), fix the code (green), and now that bug can never silently come back. And it's a great forcing function against over-engineering — since you only write enough code to pass the current test, you tend not to build speculative features nobody asked for.",
        "## When it's overkill",
        "Be honest about the limits. TDD is awkward for exploratory work — when you're not yet sure what the right API or architecture even looks like, writing tests first means writing (and rewriting) tests as your understanding changes, which can slow you down rather than help. It's also a poor fit for UI layout and visual design, where 'correct' is judged by eye, not by an assertion. And for throwaway scripts or prototypes you'll delete in a day, strict TDD is just ceremony.",
        "A realistic approach many experienced engineers use: TDD for core logic and bug fixes, a looser 'write code, then write tests soon after' approach for UI and exploratory work, and skip tests entirely for genuine one-off scripts. The goal was never 'follow TDD' — it was always 'end up with correct, well-tested code.' Use the discipline where it earns its keep.",
      ],
      takeaways: [
        "TDD is a red-green-refactor loop: fail first, pass minimally, then clean up with a safety net.",
        "Writing the test first forces clarity about interface and expected behavior before implementation details.",
        "TDD works best on well-defined logic and bug fixes where you can state inputs and outputs up front.",
        "TDD is a poor fit for exploratory work, UI design, and throwaway scripts — don't force it everywhere.",
        "The goal is well-tested correct code, not ideological adherence to a process.",
      ],
      resources: [
        { title: "Test Automation University — TDD Courses", url: "https://testautomationu.applitools.com/", note: "Look for their TDD-focused course tracks." },
        { title: "Write tests. Not too many. Mostly integration.", url: "https://kentcdodds.com/blog/write-tests", note: "Kent C. Dodds' pragmatic counterpoint on where to focus testing effort." },
        { title: "Jest Documentation — Getting Started", url: "https://jestjs.io/docs/getting-started", note: "Set up a fast test runner so the red-green loop stays quick." },
        { title: "pytest Documentation", url: "https://docs.pytest.org/en/stable/", note: "Same idea in Python — a fast loop is what makes TDD bearable." },
      ],
      tryThis: "Pick one bug in a project of yours, write a failing test that reproduces it before touching the fix, then make it pass.",
    },
    "handling-bugs-in-production": {
      body: [
        "Every system running in production will eventually break in a way nothing caught beforehand. What separates a good engineer here isn't never causing bugs — it's how calmly and effectively you respond when one shows up.",
        "## Severity triage",
        "Not every bug deserves the same response. The first move when a bug report comes in is triage: how many users are affected, is data being lost or corrupted, is money involved, is there a workaround? A typo in a rarely-visited settings page and a checkout flow that's silently double-charging customers are both 'bugs,' but they demand wildly different urgency. Most teams use a simple severity scale (something like Sev1 through Sev4) so everyone can quickly agree on how fast this needs to move and who needs to be pulled in, instead of debating it mid-crisis.",
        "## The hotfix flow",
        "For a genuine high-severity issue, the flow is usually: confirm and reproduce the bug, identify the smallest safe change that stops the bleeding (this is not the time for a big refactor), get it reviewed even if review has to be fast, deploy it, and verify in production that it actually worked. Speed matters, but 'smallest safe change' matters more — a rushed fix that introduces a second bug turns one incident into two. If you can mitigate immediately (feature flag off, roll back to the last known-good deploy) while you work on the real fix, do that first; a rollback buys you time to fix things properly without pressure.",
        "Communicate as you go. Whoever is affected — users, support, your team — should not be left guessing. A short, honest status update ('we've identified the issue, a fix is being tested, ETA 30 minutes') beats silence every time, even when you don't have a complete answer yet.",
        "## Blameless postmortems",
        "Once the fire is out, the most valuable part of the whole incident happens: figuring out why it occurred and how to prevent the category of bug from recurring, not who to blame. A blameless postmortem asks 'what in our process, tooling, or code made this possible' instead of 'who wrote the bug.' This isn't just a nicer culture — it's more effective. If people fear blame, they hide information, downplay their role, and the real cause never surfaces, so the same class of bug happens again.",
        "A good postmortem produces a timeline of what happened, the root cause, what stopped the issue from being caught earlier (was there a missing test? a missing alert?), and concrete action items with owners — often 'add a test for this case' or 'add monitoring for this metric.' That last part connects straight back to testing: a huge fraction of production incidents get turned into a regression test as part of the fix, so that specific failure literally cannot happen silently again.",
      ],
      takeaways: [
        "Triage bugs by real-world impact before deciding how urgently to respond.",
        "For high-severity bugs, prefer the smallest safe fix or a rollback over a rushed big change.",
        "Communicate status honestly and promptly to whoever is affected, even without a full answer yet.",
        "Blameless postmortems focus on process and system causes, not individual blame, because that surfaces the truth.",
        "Turn production incidents into regression tests so the same bug can't silently recur.",
      ],
      resources: [
        { title: "Test Automation University", url: "https://testautomationu.applitools.com/", note: "Includes content on regression testing strategy after incidents." },
        { title: "Jest Documentation — Getting Started", url: "https://jestjs.io/docs/getting-started", note: "Use it to turn a production bug into a fast regression test." },
        { title: "pytest Documentation", url: "https://docs.pytest.org/en/stable/", note: "Same pattern in Python: reproduce the bug as a test, then fix it." },
        { title: "Why Test?", url: "https://kentcdodds.com/blog/why-write-tests", note: "Revisit this once you've lived through an incident — it hits differently." },
      ],
      tryThis: "Write a one-paragraph blameless postmortem for a real bug you've caused or fixed: what happened, root cause, and one concrete prevention step.",
    },
  },
  quiz: {
    id: "track-quiz",
    title: "Track 5 Quiz",
    questions: [
      {
        q: "What's the main reason tests give you confidence to refactor code?",
        options: [
          "They make the code run faster",
          "They let you verify behavior is unchanged after restructuring, instead of guessing",
          "They automatically fix bugs they find",
          "They replace the need for code review",
        ],
        answer: 1,
        explanation: "Tests let you change internals and quickly confirm behavior didn't break, which is what makes refactoring safe rather than risky.",
      },
      {
        q: "Why is it a problem for a unit test to depend on a function's internal implementation details rather than its public behavior?",
        options: [
          "It makes the test run slower",
          "It breaks every time you refactor even if behavior is unchanged, eroding trust in the suite",
          "It's not actually a problem, it's the recommended approach",
          "It means the test can't use assertions",
        ],
        answer: 1,
        explanation: "Tests coupled to implementation details fail on harmless refactors, which trains people to ignore or distrust failing tests.",
      },
      {
        q: "In the testing pyramid, why do teams write far more unit tests than end-to-end tests?",
        options: [
          "Unit tests are more important to users",
          "E2E tests can't check real user flows",
          "Unit tests are fast, cheap, and isolate failures, while E2E tests are slower and more brittle",
          "Unit tests don't require any setup",
        ],
        answer: 2,
        explanation: "The pyramid shape reflects cost and speed tradeoffs: unit tests are cheap and precise, E2E tests are valuable but expensive and brittle, so you use fewer of them.",
      },
      {
        q: "In test-driven development, what happens during the 'red' step?",
        options: [
          "You delete failing tests",
          "You write a test for behavior that doesn't exist yet and confirm it fails",
          "You refactor the implementation",
          "You deploy the code to production",
        ],
        answer: 1,
        explanation: "Red means writing a test first and watching it fail, which proves the test is actually checking something that doesn't exist yet.",
      },
      {
        q: "What is the primary goal of a blameless postmortem after a production incident?",
        options: [
          "To identify which engineer should be held accountable",
          "To find process or system causes so the same class of bug doesn't recur",
          "To decide who has to write the hotfix next time",
          "To document the incident for legal purposes only",
        ],
        answer: 1,
        explanation: "Blameless postmortems focus on systemic causes because that surfaces the real information needed to prevent recurrence, whereas blame makes people hide details.",
      },
    ],
  },
  challenge: {
    id: "track-challenge",
    title: "Challenge: Test the Thing You Built",
    brief:
      "Go back to the project you built in Track 4 and add real automated tests to it. You'll write at least one happy-path test and two edge-case tests, and you'll practice the arrange-act-assert habit until it's automatic.",
    steps: [
      "Set up a test runner in your Track 4 project (Jest, Vitest, or pytest depending on your stack) if it doesn't already have one.",
      "Pick one important function or endpoint in your project — something with real logic, not a trivial getter.",
      "Write a happy-path test: typical valid input, expected correct output.",
      "Write an edge-case test for an empty or missing input (empty string, empty array, null, or missing field).",
      "Write a second edge-case test for an unusual but valid input (a boundary value, a very large input, or an unexpected-but-legal type).",
      "Run the full suite and confirm all three tests pass; then deliberately break the function and confirm at least one test fails.",
      "Write one sentence in your project README describing what the tests cover and how to run them.",
    ],
  },
};
