/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTrackIdRouteImport } from './routes/track.$trackId'
import { Route as TrackTrackIdLessonModuleIdRouteImport } from './routes/track.$trackId.lesson.$moduleId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackIdRoute = TrackTrackIdRouteImport.update({
  id: '/track/$trackId',
  path: '/track/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackIdLessonModuleIdRoute =
  TrackTrackIdLessonModuleIdRouteImport.update({
    id: '/lesson/$moduleId',
    path: '/lesson/$moduleId',
    getParentRoute: () => TrackTrackIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track/$trackId': typeof TrackTrackIdRouteWithChildren
  '/track/$trackId/lesson/$moduleId': typeof TrackTrackIdLessonModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track/$trackId': typeof TrackTrackIdRouteWithChildren
  '/track/$trackId/lesson/$moduleId': typeof TrackTrackIdLessonModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track/$trackId': typeof TrackTrackIdRouteWithChildren
  '/track/$trackId/lesson/$moduleId': typeof TrackTrackIdLessonModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/track/$trackId'
    | '/track/$trackId/lesson/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/track/$trackId'
    | '/track/$trackId/lesson/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/track/$trackId'
    | '/track/$trackId/lesson/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackTrackIdRoute: typeof TrackTrackIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackId/lesson/$moduleId': {
      id: '/track/$trackId/lesson/$moduleId'
      path: '/lesson/$moduleId'
      fullPath: '/track/$trackId/lesson/$moduleId'
      preLoaderRoute: typeof TrackTrackIdLessonModuleIdRouteImport
      parentRoute: typeof TrackTrackIdRoute
    }
  }
}

interface TrackTrackIdRouteChildren {
  TrackTrackIdLessonModuleIdRoute: typeof TrackTrackIdLessonModuleIdRoute
}

const TrackTrackIdRouteChildren: TrackTrackIdRouteChildren = {
  TrackTrackIdLessonModuleIdRoute: TrackTrackIdLessonModuleIdRoute,
}

const TrackTrackIdRouteWithChildren = TrackTrackIdRoute._addFileChildren(
  TrackTrackIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackTrackIdRoute: TrackTrackIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
